export const UserInit = {
  _id: "",
  email: "",
  fullName: "",
  userName: "",
  age: 0,
  coin: 0,
  reward: 0,
  role: "",
  profileImage: "",
  history: [],
  redeemedRewards: [],
  createdAt: "",
  updatedAt: "",
  rewardPoints: 0,
  __v: 0,
};
